version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - .:/app
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/app
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - php

networks:
  app-network:
    driver: bridge

